workflows:
  android-release:
    name: "Chikuu Android Build"
    max_build_duration: 60
    instance_type: mac_mini_m2  # या linux_x2 अगर MacOS नहीं चाहिए
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: "Clean Project"
        script: ./gradlew clean
      - name: "Build Release APK"
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
