workflows:
  chikuu_flutter_autofix:
    name: Chikuu Flutter AutoFix Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.chikuu.app"
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Auto-fix dependencies
        script: |
          flutter pub upgrade --major-versions
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build AppBundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        recipients:
          - your@email.com
