workflows:
  chikuu-android-build:
    name: Chikuu Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.chikuu.app"
      flutter: stable
      java: 17
      android:
        build: gradle
    scripts:
      - name: Clean Project
        script: |
          cd android
          ./gradlew clean
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs//*.apk
    publishing:
      email:
        recipients:
          - "your-email@example.com"
