workflows:
  android-release:
    name: "Chikuu Android Build"
    max_build_duration: 60
    environment:
      groups:
        - default
      vars:
        JAVA_VERSION: 17
      android:
        image: latest
    scripts:
      - name: "Clean Project"
        script: ./gradlew clean
      - name: "Build Release APK"
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
