name: chikuu
description: "A premium, secure, cross-platform romantic/cute games and chat app."
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.19.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.8
  firebase_database: ^11.7.0
  firebase_storage: ^12.4.0
  firebase_messaging: ^14.9.1
  provider: ^6.1.2
  webview_flutter: ^4.7.0
  flutter_webrtc: ^0.9.47
  lottie: ^2.7.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf