name: chikuu
description: "A premium, secure, cross-platform romantic/cute games and chat app."
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase (all updated for Flutter 3.x)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.3.3
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.2.3

  # State management
  provider: ^6.1.2

  # WebView
  webview_flutter: ^4.7.0

  # WebRTC (updated for Flutter 3.22+)
  flutter_webrtc: ^1.0.4

  # Animations & UI
  lottie: ^3.1.2
  google_fonts: ^6.2.1

  # HTTP requests
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
